package ru.headh.kosti.telegrambot.util

const val MAIN_MENU = "MAIN_MENU"
const val HOME_MENU = "HOME_MENU"
const val DEVICE_MENU = "DEVICE_MENU"

const val DELETE_USER = "DELETE_USER"
const val SIGN_OUT = "SIGN_OUT"
const val PROFILE = "PROFILE"

const val CREATE_HOME = "CREATE_HOME"
const val UPDATE_HOME = "UPDATE_HOME"
const val DELETE_HOME = "DELETE_HOME"
const val GET_HOME = "GET_HOME"
const val GET_HOME_LIST = "GET_HOME_LIST"

const val CREATE_ROOM = "CREATE_ROOM"
const val DELETE_ROOM = "DELETE_ROOM"
const val GET_ROOM = "GET_ROOM"
const val UPDATE_ROOM = "UPDATE_ROOM"
const val GET_ROOM_LIST = "GET_ROOM_LIST"

const val GET_DEVICE_LIST = "GET_DEVICE_LIST"
const val CREATE_DEVICE = "CREATE_DEVICE"
const val RENAME_DEVICE = "RENAME_DEVICE"
const val CHANGE_DEVICE_HOME = "RENAME_DEVICE"
const val CHANGE_DEVICE_ROOM = "CHANGE_DEVICE_ROOM"
const val GET_DEVICE = "GET_DEVICE"
const val DELETE_DEVICE = "DELETE_DEVICE"
const val CHANGE_DEVICE_STATE = "CHANGE_DEVICE_STATE"