server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/home_service_db
    username: admin
    password: admin
    generate-dll: none

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: db/changelog-master.yaml
    enabled: true

springdoc:
  swagger-ui:
    enabled: true
    path: /swag
    disable-swagger-default-url: true
  show-actuator: false