spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/HOME_SERVICE_DB
    username: postgres
    password: 1111
    generate-dll: none

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: db/changelog-master.yaml
    enabled: true
