server:
  port: 8081

connector:
  region: EU
  ak: ${TUYA_AK:94cym9d9ykqmjpaptd9y}
  sk: ${TUYA_SK:3a19c60c927d46ebbcd32a325b6a17ca}

spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/device-service-db}
    username: ${POSTGRES_USERNAME:admin}
    password: ${POSTGRES_PASSWORD:admin}
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    properties:
      hibernate:
        format_sql: true
  application:
    name: device-service
  kafka:
    bootstrap-servers: ${KAFKA_SERVER:localhost:29092}

  liquibase:
    change-log: db/changelog-master.yaml
    enabled: true

home-service:
  url: ${HOME_SERVICE_URL:http://localhost:8082/api/homes/check/}

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    disable-swagger-default-url: true
  show-actuator: false