server:
  port: 8079

jwt:
  secret: hjhbjhbJHBJHFBDjhbjhb873Y4UI2BUYLSDLDBjgf

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    disable-swagger-default-url: true
  show-actuator: false
