server:
  port: 8081

connector:
  region: EU
  ak: 94cym9d9ykqmjpaptd9y
  sk: 3a19c60c927d46ebbcd32a325b6a17ca

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/device-service-db
    username: admin
    password: admin
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    properties:
      hibernate:
        format_sql: true
  application:
    name: device-service
  kafka:
    bootstrap-servers: localhost:29092

  liquibase:
    change-log: db/changelog-master.yaml
    enabled: true

springdoc:
  swagger-ui:
    enabled: true
    path: /swag
    disable-swagger-default-url: true
  show-actuator: false