server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users_headh_db
    username: admin
    password: admin
  liquibase:
    change-log: classpath:/db/changelog-master.yaml
    enabled: true
  application:
    name: user-service
  kafka:
    bootstrap-servers: localhost:29092

springdoc:
  swagger-ui:
    enabled: true
    path: /swag
    disable-swagger-default-url: true
  show-actuator: false