server:
  port: 8080

connector:
  region: EU
  ak: 94cym9d9ykqmjpaptd9y
  sk: 3a19c60c927d46ebbcd32a325b6a17ca

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/device-service-db
    username: admin
    password: admin
  # TODO Сделать миграции
  jpa:
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: update
